set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${DAGSTER_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${DAGSTER_DB} TO ${PG_USER};
    CREATE DATABASE ${MLFLOW_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${MLFLOW_DB} TO ${PG_USER};
EOSQL